sudo: required #is required to use docker service in travis

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=kamynina/pgtap
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64

language: sql #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 - docker build -t level-three-rest -t $REPO:$TAG -f Dockerfile .

after_success:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWD
  - export REPO=kamynina/pgtap
  - export TAG=`if [ "$TRAVIS_BRANCH" = "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
